    #[test]
    fn recent_raw_staged_window_seeding_current_start_matches_neither_promoted_nor_source_stage1(
    ) -> Result<()> {
        let fixture = make_recent_raw_promotion_fixture(
            "recent-raw-staged-window-seeding-internal-checkpoint",
            SourceStateSeed::Missing,
        )?;
        fixture.rewrite_source_state(
            &[
                swap(
                    "wallet-raw",
                    "sig-source-a",
                    parse_ts("2026-04-14T07:54:00Z")?,
                    SOL_MINT,
                    "TokenRaw111111111111111111111111111111111",
                    1.0,
                    9.0,
                ),
                swap(
                    "wallet-raw",
                    "sig-source-b",
                    parse_ts("2026-04-14T07:56:00Z")?,
                    SOL_MINT,
                    "TokenRaw111111111111111111111111111111111",
                    1.0,
                    11.0,
                ),
                swap(
                    "wallet-raw",
                    "sig-z-source-c",
                    parse_ts("2026-04-14T07:57:00Z")?,
                    SOL_MINT,
                    "TokenRaw111111111111111111111111111111111",
                    1.0,
                    12.0,
                ),
            ],
            parse_ts("2026-04-14T08:07:00Z")?,
        )?;
        fixture.write_promoted_surface_with_covered_since(
            "latest.sqlite",
            parse_ts("2026-04-14T07:55:00Z")?,
            2,
            parse_ts("2026-04-14T07:56:00Z")?,
            "sig-source-b",
            parse_ts("2026-04-14T08:00:00Z")?,
        )?;
        fixture.write_selected_staged_surface_sqlite_with_source_path_and_created_at(
            &fixture.runtime_db_path,
            &[
                swap(
                    "wallet-raw",
                    "sig-staged-a",
                    parse_ts("2026-04-14T07:56:00Z")?,
                    SOL_MINT,
                    "TokenRaw111111111111111111111111111111111",
                    1.0,
                    10.0,
                ),
                swap(
                    "wallet-raw",
                    "sig-staged-b",
                    parse_ts("2026-04-14T07:57:00Z")?,
                    SOL_MINT,
                    "TokenRaw111111111111111111111111111111111",
                    1.0,
                    11.0,
                ),
            ],
            parse_ts("2026-04-14T08:02:00Z")?,
            parse_ts("2026-04-14T08:03:00Z")?,
        )?;

        let diagnostic = DiscoveryService::explain_recent_raw_staged_window_seeding_read_only(
            &fixture.state_root,
        )?;
        assert_eq!(
            diagnostic.recent_raw_staged_window_seeding_reason_class,
            RecentRawStagedWindowSeedingReasonClass::RecentRawStagedWindowCurrentStartMatchesNeitherPromotedNorSource
        );
        assert!(diagnostic.recent_raw_staged_window_seeding_observed);
        assert!(
            !diagnostic
                .recent_raw_staged_window_historical_seeding_basis_proven_from_current_artifacts
        );
        assert_eq!(
            diagnostic.recent_raw_staged_start_current_evidence_basis,
            RecentRawStagedWindowSeedingBasis::MatchesNeitherPromotedNorCurrentSourceStart
        );
        assert_eq!(
            diagnostic.recent_raw_staged_start_matches_promoted_start,
            Some(false)
        );
        assert_eq!(
            diagnostic.recent_raw_staged_start_matches_current_window_cutoff,
            Some(false)
        );
        assert_eq!(
            diagnostic.recent_raw_staged_start_matches_neither_promoted_nor_source,
            Some(true)
        );
        assert_eq!(
            diagnostic.recent_raw_promoted_can_seed_staged_progress_under_current_code,
            Some(false)
        );
        Ok(())
    }

    #[test]
    fn recent_raw_staged_window_seeding_unproven_case_stage1() -> Result<()> {
        let fixture = make_recent_raw_promotion_fixture(
            "recent-raw-staged-window-seeding-unproven",
            SourceStateSeed::StagedCurrent,
        )?;
        fixture.write_promoted_surface(
            "latest.sqlite",
            2,
            parse_ts("2026-04-14T07:56:00Z")?,
            "sig-promoted",
            parse_ts("2026-04-14T08:00:00Z")?,
        )?;
        fixture.write_staged_surface(
            1,
            parse_ts("2026-04-14T07:55:30Z")?,
            "sig-staged",
            parse_ts("2026-04-14T08:03:00Z")?,
        )?;

        let diagnostic = DiscoveryService::explain_recent_raw_staged_window_seeding_read_only(
            &fixture.state_root,
        )?;
        assert_eq!(
            diagnostic.recent_raw_staged_window_seeding_reason_class,
            RecentRawStagedWindowSeedingReasonClass::RecentRawStagedWindowCurrentEvidenceUnprovenDueToMissingEvidence
        );
        assert!(!diagnostic.recent_raw_staged_window_seeding_observed);
        assert!(
            !diagnostic
                .recent_raw_staged_window_historical_seeding_basis_proven_from_current_artifacts
        );
        assert_eq!(
            diagnostic.recent_raw_staged_start_current_evidence_basis,
            RecentRawStagedWindowSeedingBasis::Unproven
        );
        assert!(diagnostic.recent_raw_staged_manifest_sqlite_match_unproven);
        Ok(())
    }

    #[test]
    fn recent_raw_staged_window_seeding_includes_explicit_basis_fields_stage1() -> Result<()> {
        let fixture = make_recent_raw_promotion_fixture(
            "recent-raw-staged-window-seeding-fields",
            SourceStateSeed::Missing,
        )?;
        fixture.rewrite_source_state(
            &[
                swap(
                    "wallet-raw",
                    "sig-source-a",
                    parse_ts("2026-04-14T07:56:00Z")?,
                    SOL_MINT,
                    "TokenRaw111111111111111111111111111111111",
                    1.0,
                    10.0,
                ),
                swap(
                    "wallet-raw",
                    "sig-source-b",
                    parse_ts("2026-04-14T07:57:00Z")?,
                    SOL_MINT,
                    "TokenRaw111111111111111111111111111111111",
                    1.0,
                    11.0,
                ),
            ],
            parse_ts("2026-04-14T08:07:00Z")?,
        )?;
        fixture.write_promoted_surface_with_covered_since(
            "latest.sqlite",
            parse_ts("2026-04-14T07:55:00Z")?,
            1,
            parse_ts("2026-04-14T07:56:00Z")?,
            "sig-promoted",
            parse_ts("2026-04-14T08:00:00Z")?,
        )?;
        fixture.write_selected_staged_surface_sqlite_with_source_path_and_created_at(
            &fixture.runtime_db_path,
            &[swap(
                "wallet-raw",
                "sig-staged",
                parse_ts("2026-04-14T07:56:00Z")?,
                SOL_MINT,
                "TokenRaw111111111111111111111111111111111",
                1.0,
                10.0,
            )],
            parse_ts("2026-04-14T08:01:00Z")?,
            parse_ts("2026-04-14T08:03:00Z")?,
        )?;

        let diagnostic = DiscoveryService::explain_recent_raw_staged_window_seeding_read_only(
            &fixture.state_root,
        )?;
        assert!(diagnostic.recent_raw_promoted_covered_since.is_some());
        assert!(diagnostic.recent_raw_staged_covered_since.is_some());
        assert!(diagnostic.recent_raw_source_covered_since.is_some());
        assert_eq!(
            diagnostic.recent_raw_staged_start_matches_promoted_start,
            Some(false)
        );
        assert_eq!(
            diagnostic.recent_raw_staged_start_matches_source_start,
            Some(true)
        );
        assert_eq!(
            diagnostic.recent_raw_staged_start_matches_current_window_cutoff,
            Some(true)
        );
        assert_eq!(
            diagnostic.recent_raw_staged_start_matches_neither_promoted_nor_source,
            Some(false)
        );
        assert!(
            !diagnostic
                .recent_raw_staged_window_historical_seeding_basis_proven_from_current_artifacts
        );
        assert!(!diagnostic
            .recent_raw_staged_start_current_evidence_explanation
            .is_empty());
        Ok(())
    }

    #[test]
    fn recent_raw_staged_window_seeding_explain_remains_read_only_stage1() -> Result<()> {
        let fixture = make_recent_raw_promotion_fixture(
            "recent-raw-staged-window-seeding-read-only",
            SourceStateSeed::Missing,
        )?;
        fixture.rewrite_source_state(
            &[
                swap(
                    "wallet-raw",
                    "sig-source-a",
                    parse_ts("2026-04-14T07:56:00Z")?,
                    SOL_MINT,
                    "TokenRaw111111111111111111111111111111111",
                    1.0,
                    10.0,
                ),
                swap(
                    "wallet-raw",
                    "sig-source-b",
                    parse_ts("2026-04-14T07:57:00Z")?,
                    SOL_MINT,
                    "TokenRaw111111111111111111111111111111111",
                    1.0,
                    11.0,
                ),
            ],
            parse_ts("2026-04-14T08:07:00Z")?,
        )?;
        fixture.write_promoted_surface_with_covered_since(
            "latest.sqlite",
            parse_ts("2026-04-14T07:55:00Z")?,
            1,
            parse_ts("2026-04-14T07:56:00Z")?,
            "sig-promoted",
            parse_ts("2026-04-14T08:00:00Z")?,
        )?;
        fixture.write_selected_staged_surface_sqlite_with_source_path_and_created_at(
            &fixture.runtime_db_path,
            &[swap(
                "wallet-raw",
                "sig-staged",
                parse_ts("2026-04-14T07:56:00Z")?,
                SOL_MINT,
                "TokenRaw111111111111111111111111111111111",
                1.0,
                10.0,
            )],
            parse_ts("2026-04-14T08:01:00Z")?,
            parse_ts("2026-04-14T08:03:00Z")?,
        )?;

        let before = fixture.capture_bytes()?;
        let _ = DiscoveryService::explain_recent_raw_staged_window_seeding_read_only(
            &fixture.state_root,
        )?;
        let after = fixture.capture_bytes()?;
        assert_eq!(before, after);
        Ok(())
    }

    #[test]
    fn recent_raw_source_window_contract_matches_promoted_start_stage1() -> Result<()> {
        let fixture = make_recent_raw_promotion_fixture(
            "recent-raw-source-window-contract-matches-promoted-start",
            SourceStateSeed::Missing,
        )?;
        fixture.rewrite_source_state(
            &[
                swap(
                    "wallet-raw",
                    "sig-source-a",
                    parse_ts("2026-04-14T07:55:00Z")?,
                    SOL_MINT,
                    "TokenRaw111111111111111111111111111111111",
                    1.0,
                    10.0,
                ),
                swap(
                    "wallet-raw",
                    "sig-source-b",
                    parse_ts("2026-04-14T07:56:00Z")?,
                    SOL_MINT,
                    "TokenRaw111111111111111111111111111111111",
                    1.0,
                    11.0,
                ),
            ],
            parse_ts("2026-04-14T08:06:00Z")?,
        )?;
        fixture.write_promoted_surface_with_covered_since(
            "latest.sqlite",
            parse_ts("2026-04-14T07:55:00Z")?,
            1,
            parse_ts("2026-04-14T07:56:00Z")?,
            "sig-promoted",
            parse_ts("2026-04-14T08:00:00Z")?,
        )?;

        let diagnostic = DiscoveryService::explain_recent_raw_source_window_contract_read_only(
            &fixture.state_root,
        )?;
        assert_eq!(
            diagnostic.recent_raw_source_window_contract_reason_class,
            RecentRawSourceWindowContractReasonClass::RecentRawSourceWindowCurrentStartMatchesPromotedStart
        );
        assert!(diagnostic.recent_raw_source_window_contract_observed);
        assert_eq!(
            diagnostic.recent_raw_source_start_later_than_promoted,
            Some(false)
        );
        assert_eq!(
            diagnostic.recent_raw_source_window_matches_current_bounded_contract,
            Some(true)
        );
        assert!(diagnostic.recent_raw_source_window_probe_bounded);
        assert_eq!(
            diagnostic.recent_raw_source_window_probe_mode,
            RecentRawSourceWindowProbeMode::BoundedIndexEdges
        );
        assert_eq!(
            diagnostic.recent_raw_source_cached_state_matches_bounded_probe,
            Some(true)
        );
        assert!(diagnostic
            .recent_raw_source_bounded_probe_covered_since
            .is_some());
        assert!(diagnostic
            .recent_raw_source_bounded_probe_covered_through
            .is_some());
        assert_eq!(diagnostic.recent_raw_source_scanned_covered_since, None);
        assert_eq!(diagnostic.recent_raw_source_scanned_covered_through, None);
        assert_eq!(diagnostic.recent_raw_source_scanned_row_count, None);
        assert_eq!(
            diagnostic.recent_raw_source_cached_state_matches_scanned_rows,
            None
        );
        assert_eq!(
            diagnostic.recent_raw_source_window_contract_basis,
            RecentRawSourceWindowContractBasis::MatchesPromotedStart
        );
        Ok(())
    }

    #[test]
    fn recent_raw_source_window_contract_excludes_older_rows_stage1() -> Result<()> {
        let fixture = make_recent_raw_promotion_fixture(
            "recent-raw-source-window-contract-excludes-older-rows",
            SourceStateSeed::Missing,
        )?;
        fixture.rewrite_source_state(
            &[
                swap(
                    "wallet-raw",
                    "sig-source-old",
                    parse_ts("2026-04-14T07:54:00Z")?,
                    SOL_MINT,
                    "TokenRaw111111111111111111111111111111111",
                    1.0,
                    9.0,
                ),
                swap(
                    "wallet-raw",
                    "sig-source-a",
                    parse_ts("2026-04-14T07:56:00Z")?,
                    SOL_MINT,
                    "TokenRaw111111111111111111111111111111111",
                    1.0,
                    10.0,
                ),
                swap(
                    "wallet-raw",
                    "sig-source-b",
                    parse_ts("2026-04-14T07:57:00Z")?,
                    SOL_MINT,
                    "TokenRaw111111111111111111111111111111111",
                    1.0,
                    11.0,
                ),
            ],
            parse_ts("2026-04-14T08:06:00Z")?,
        )?;
        fixture.prune_source_state_before(
            parse_ts("2026-04-14T07:56:00Z")?,
            32,
            parse_ts("2026-04-14T08:07:00Z")?,
        )?;
        fixture.write_promoted_surface_with_covered_since(
            "latest.sqlite",
            parse_ts("2026-04-14T07:55:00Z")?,
            2,
            parse_ts("2026-04-14T07:57:00Z")?,
            "sig-promoted",
            parse_ts("2026-04-14T08:00:00Z")?,
        )?;

        let diagnostic = DiscoveryService::explain_recent_raw_source_window_contract_read_only(
            &fixture.state_root,
        )?;
        assert_eq!(
            diagnostic.recent_raw_source_window_contract_reason_class,
            RecentRawSourceWindowContractReasonClass::RecentRawSourceWindowCurrentContractExcludesOlderRows
        );
        assert!(diagnostic.recent_raw_source_window_contract_observed);
        assert_eq!(
            diagnostic.recent_raw_source_start_later_than_promoted,
            Some(true)
        );
        assert_eq!(
            diagnostic.recent_raw_source_contract_currently_excludes_older_rows,
            Some(true)
        );
        assert_eq!(
            diagnostic.recent_raw_source_window_matches_current_bounded_contract,
            Some(true)
        );
        assert!(diagnostic.recent_raw_source_window_probe_bounded);
        assert_eq!(
            diagnostic.recent_raw_source_window_probe_mode,
            RecentRawSourceWindowProbeMode::BoundedIndexEdges
        );
        assert_eq!(
            diagnostic.recent_raw_source_cached_state_matches_bounded_probe,
            Some(true)
        );
        assert!(diagnostic
            .recent_raw_source_bounded_probe_covered_since
            .is_some());
        assert!(diagnostic
            .recent_raw_source_bounded_probe_covered_through
            .is_some());
        assert_eq!(diagnostic.recent_raw_source_scanned_covered_since, None);
        assert_eq!(diagnostic.recent_raw_source_scanned_covered_through, None);
        assert_eq!(diagnostic.recent_raw_source_scanned_row_count, None);
        assert_eq!(
            diagnostic.recent_raw_source_cached_state_matches_scanned_rows,
            None
        );
        assert_eq!(
            diagnostic.recent_raw_source_prune_activity_recorded,
            Some(true)
        );
        assert_eq!(
            diagnostic.recent_raw_source_window_contract_basis,
            RecentRawSourceWindowContractBasis::CurrentSourceObservedSwapsWindowExcludesOlderRows
        );
        Ok(())
    }
