    #[test]
    fn recent_raw_replacement_progress_contract_advancing_but_incomplete_stage1() -> Result<()> {
        let fixture = make_recent_raw_promotion_fixture(
            "recent-raw-replacement-progress-contract-advancing",
            SourceStateSeed::Missing,
        )?;
        fixture.rewrite_source_state(
            &[
                swap(
                    "wallet-raw",
                    "sig-source-a",
                    parse_ts("2026-04-14T07:56:00Z")?,
                    SOL_MINT,
                    "TokenRaw111111111111111111111111111111111",
                    1.0,
                    10.0,
                ),
                swap(
                    "wallet-raw",
                    "sig-source-b",
                    parse_ts("2026-04-14T07:57:00Z")?,
                    SOL_MINT,
                    "TokenRaw111111111111111111111111111111111",
                    1.0,
                    11.0,
                ),
                swap(
                    "wallet-raw",
                    "sig-source-c",
                    parse_ts("2026-04-14T07:58:00Z")?,
                    SOL_MINT,
                    "TokenRaw111111111111111111111111111111111",
                    1.0,
                    12.0,
                ),
            ],
            parse_ts("2026-04-14T08:12:00Z")?,
        )?;
        fixture.write_promoted_surface_with_covered_since(
            "latest.sqlite",
            parse_ts("2026-04-14T07:55:00Z")?,
            2,
            parse_ts("2026-04-14T07:56:00Z")?,
            "sig-promoted",
            parse_ts("2026-04-14T08:00:00Z")?,
        )?;
        fixture.write_selected_staged_surface_sqlite_with_source_path_and_created_at(
            &fixture.runtime_db_path,
            &[
                swap(
                    "wallet-raw",
                    "sig-source-a",
                    parse_ts("2026-04-14T07:56:00Z")?,
                    SOL_MINT,
                    "TokenRaw111111111111111111111111111111111",
                    1.0,
                    10.0,
                ),
                swap(
                    "wallet-raw",
                    "sig-source-b",
                    parse_ts("2026-04-14T07:57:00Z")?,
                    SOL_MINT,
                    "TokenRaw111111111111111111111111111111111",
                    1.0,
                    11.0,
                ),
            ],
            parse_ts("2026-04-14T08:10:00Z")?,
            parse_ts("2026-04-14T08:05:00Z")?,
        )?;
        fixture.write_named_staged_candidate_surface_with_source_path_and_covered_since(
            ".discovery_recent_raw_staged.sqlite.archive-staged.prev",
            &fixture.runtime_db_path,
            parse_ts("2026-04-14T07:56:00Z")?,
            1,
            parse_ts("2026-04-14T07:56:00Z")?,
            "sig-source-a",
            parse_ts("2026-04-14T08:05:00Z")?,
        )?;

        let diagnostic =
            DiscoveryService::explain_recent_raw_replacement_progress_contract_read_only(
                &fixture.state_root,
            )?;
        assert_eq!(
            diagnostic.recent_raw_replacement_progress_reason_class,
            RecentRawReplacementProgressReasonClass::RecentRawReplacementProgressAdvancingButIncomplete
        );
        assert!(diagnostic.recent_raw_replacement_progress_observed);
        assert!(diagnostic.recent_raw_replacement_candidate_exists);
        assert_eq!(
            diagnostic.recent_raw_replacement_candidate_same_identity_as_previous_attempt,
            Some(true)
        );
        assert_eq!(
            diagnostic.recent_raw_replacement_candidate_row_count_advanced,
            Some(true)
        );
        assert_eq!(
            diagnostic.recent_raw_replacement_candidate_covered_through_advanced,
            Some(true)
        );
        assert_eq!(
            diagnostic.recent_raw_replacement_candidate_last_batch_completed_at_advanced,
            Some(true)
        );
        assert_eq!(
            diagnostic.recent_raw_replacement_candidate_completed_after_creation,
            Some(true)
        );
        assert_eq!(
            diagnostic.recent_raw_replacement_candidate_advancing,
            Some(true)
        );
        assert_eq!(
            diagnostic.recent_raw_replacement_candidate_stalled,
            Some(false)
        );
        assert_eq!(
            diagnostic.recent_raw_replacement_candidate_reset_or_recreated,
            Some(false)
        );
        Ok(())
    }

    #[test]
    fn recent_raw_replacement_progress_contract_stalled_case_stage1() -> Result<()> {
        let fixture = make_recent_raw_promotion_fixture(
            "recent-raw-replacement-progress-contract-stalled",
            SourceStateSeed::Missing,
        )?;
        fixture.rewrite_source_state(
            &[
                swap(
                    "wallet-raw",
                    "sig-source-a",
                    parse_ts("2026-04-14T07:56:00Z")?,
                    SOL_MINT,
                    "TokenRaw111111111111111111111111111111111",
                    1.0,
                    10.0,
                ),
                swap(
                    "wallet-raw",
                    "sig-source-b",
                    parse_ts("2026-04-14T07:57:00Z")?,
                    SOL_MINT,
                    "TokenRaw111111111111111111111111111111111",
                    1.0,
                    11.0,
                ),
            ],
            parse_ts("2026-04-14T08:12:00Z")?,
        )?;
        fixture.write_promoted_surface_with_covered_since(
            "latest.sqlite",
            parse_ts("2026-04-14T07:55:00Z")?,
            2,
            parse_ts("2026-04-14T07:56:00Z")?,
            "sig-promoted",
            parse_ts("2026-04-14T08:00:00Z")?,
        )?;
        fixture.write_selected_staged_surface_sqlite_with_source_path_and_created_at(
            &fixture.runtime_db_path,
            &[swap(
                "wallet-raw",
                "sig-source-a",
                parse_ts("2026-04-14T07:56:00Z")?,
                SOL_MINT,
                "TokenRaw111111111111111111111111111111111",
                1.0,
                10.0,
            )],
            parse_ts("2026-04-14T08:05:00Z")?,
            parse_ts("2026-04-14T08:05:00Z")?,
        )?;
        fixture.write_named_staged_candidate_surface_with_source_path_and_covered_since(
            ".discovery_recent_raw_staged.sqlite.archive-staged.prev",
            &fixture.runtime_db_path,
            parse_ts("2026-04-14T07:56:00Z")?,
            1,
            parse_ts("2026-04-14T07:56:00Z")?,
            "sig-source-a",
            parse_ts("2026-04-14T08:05:00Z")?,
        )?;

        let diagnostic =
            DiscoveryService::explain_recent_raw_replacement_progress_contract_read_only(
                &fixture.state_root,
            )?;
        assert_eq!(
            diagnostic.recent_raw_replacement_progress_reason_class,
            RecentRawReplacementProgressReasonClass::RecentRawReplacementProgressStalledOnSameCandidate
        );
        assert!(diagnostic.recent_raw_replacement_progress_observed);
        assert_eq!(
            diagnostic.recent_raw_replacement_candidate_same_identity_as_previous_attempt,
            Some(true)
        );
        assert_eq!(
            diagnostic.recent_raw_replacement_candidate_row_count_advanced,
            Some(false)
        );
        assert_eq!(
            diagnostic.recent_raw_replacement_candidate_covered_through_advanced,
            Some(false)
        );
        assert_eq!(
            diagnostic.recent_raw_replacement_candidate_last_batch_completed_at_advanced,
            Some(false)
        );
        assert_eq!(
            diagnostic.recent_raw_replacement_candidate_advancing,
            Some(false)
        );
        assert_eq!(
            diagnostic.recent_raw_replacement_candidate_stalled,
            Some(true)
        );
        assert_eq!(
            diagnostic.recent_raw_replacement_candidate_reset_or_recreated,
            Some(false)
        );
        Ok(())
    }

    #[test]
    fn recent_raw_replacement_progress_contract_reset_or_recreated_case_stage1() -> Result<()> {
        let fixture = make_recent_raw_promotion_fixture(
            "recent-raw-replacement-progress-contract-reset",
            SourceStateSeed::Missing,
        )?;
        fixture.rewrite_source_state(
            &[
                swap(
                    "wallet-raw",
                    "sig-source-a",
                    parse_ts("2026-04-14T07:56:00Z")?,
                    SOL_MINT,
                    "TokenRaw111111111111111111111111111111111",
                    1.0,
                    10.0,
                ),
                swap(
                    "wallet-raw",
                    "sig-source-b",
                    parse_ts("2026-04-14T07:57:00Z")?,
                    SOL_MINT,
                    "TokenRaw111111111111111111111111111111111",
                    1.0,
                    11.0,
                ),
            ],
            parse_ts("2026-04-14T08:12:00Z")?,
        )?;
        fixture.write_promoted_surface_with_covered_since(
            "latest.sqlite",
            parse_ts("2026-04-14T07:55:00Z")?,
            2,
            parse_ts("2026-04-14T07:56:00Z")?,
            "sig-promoted",
            parse_ts("2026-04-14T08:00:00Z")?,
        )?;
        fixture.write_selected_staged_surface_sqlite_with_source_path_and_created_at(
            &fixture.runtime_db_path,
            &[swap(
                "wallet-raw",
                "sig-source-a",
                parse_ts("2026-04-14T07:56:00Z")?,
                SOL_MINT,
                "TokenRaw111111111111111111111111111111111",
                1.0,
                10.0,
            )],
            parse_ts("2026-04-14T08:10:00Z")?,
            parse_ts("2026-04-14T08:10:00Z")?,
        )?;
        fixture.write_named_staged_candidate_surface_with_source_path_and_covered_since(
            ".discovery_recent_raw_staged.sqlite.archive-staged.prev",
            &fixture.runtime_db_path,
            parse_ts("2026-04-14T07:56:00Z")?,
            2,
            parse_ts("2026-04-14T07:57:00Z")?,
            "sig-source-b",
            parse_ts("2026-04-14T08:05:00Z")?,
        )?;

        let diagnostic =
            DiscoveryService::explain_recent_raw_replacement_progress_contract_read_only(
                &fixture.state_root,
            )?;
        assert_eq!(
            diagnostic.recent_raw_replacement_progress_reason_class,
            RecentRawReplacementProgressReasonClass::RecentRawReplacementProgressResetOrRecreated
        );
        assert!(diagnostic.recent_raw_replacement_progress_observed);
        assert_eq!(
            diagnostic.recent_raw_replacement_candidate_same_identity_as_previous_attempt,
            Some(false)
        );
        assert_eq!(
            diagnostic.recent_raw_replacement_candidate_reset_or_recreated,
            Some(true)
        );
        Ok(())
    }

    #[test]
    fn recent_raw_replacement_progress_contract_unproven_case_stage1() -> Result<()> {
        let fixture = make_recent_raw_promotion_fixture(
            "recent-raw-replacement-progress-contract-unproven",
            SourceStateSeed::Missing,
        )?;
        fixture.rewrite_source_state(
            &[
                swap(
                    "wallet-raw",
                    "sig-source-a",
                    parse_ts("2026-04-14T07:56:00Z")?,
                    SOL_MINT,
                    "TokenRaw111111111111111111111111111111111",
                    1.0,
                    10.0,
                ),
                swap(
                    "wallet-raw",
                    "sig-source-b",
                    parse_ts("2026-04-14T07:57:00Z")?,
                    SOL_MINT,
                    "TokenRaw111111111111111111111111111111111",
                    1.0,
                    11.0,
                ),
            ],
            parse_ts("2026-04-14T08:12:00Z")?,
        )?;
        fixture.write_promoted_surface_with_covered_since(
            "latest.sqlite",
            parse_ts("2026-04-14T07:55:00Z")?,
            2,
            parse_ts("2026-04-14T07:56:00Z")?,
            "sig-promoted",
            parse_ts("2026-04-14T08:00:00Z")?,
        )?;
        fixture.write_selected_staged_surface_sqlite_with_source_path_and_created_at(
            &fixture.runtime_db_path,
            &[swap(
                "wallet-raw",
                "sig-source-a",
                parse_ts("2026-04-14T07:56:00Z")?,
                SOL_MINT,
                "TokenRaw111111111111111111111111111111111",
                1.0,
                10.0,
            )],
            parse_ts("2026-04-14T08:10:00Z")?,
            parse_ts("2026-04-14T08:05:00Z")?,
        )?;

        let diagnostic =
            DiscoveryService::explain_recent_raw_replacement_progress_contract_read_only(
                &fixture.state_root,
            )?;
        assert_eq!(
            diagnostic.recent_raw_replacement_progress_reason_class,
            RecentRawReplacementProgressReasonClass::RecentRawReplacementProgressUnprovenDueToMissingEvidence
        );
        assert!(!diagnostic.recent_raw_replacement_progress_observed);
        assert_eq!(
            diagnostic.recent_raw_replacement_candidate_same_identity_as_previous_attempt,
            None
        );
        assert_eq!(
            diagnostic.recent_raw_replacement_candidate_completed_after_creation,
            Some(true)
        );
        assert_eq!(
            diagnostic.recent_raw_replacement_candidate_row_count_advanced,
            None
        );
        assert_eq!(
            diagnostic.recent_raw_replacement_candidate_covered_through_advanced,
            None
        );
        assert_eq!(
            diagnostic.recent_raw_replacement_candidate_last_batch_completed_at_advanced,
            None
        );
        assert_eq!(diagnostic.recent_raw_replacement_candidate_advancing, None);
        assert_eq!(diagnostic.recent_raw_replacement_candidate_stalled, None);
        Ok(())
    }

    #[test]
    fn recent_raw_replacement_progress_contract_includes_explicit_fields_stage1() -> Result<()> {
        let fixture = make_recent_raw_promotion_fixture(
            "recent-raw-replacement-progress-contract-fields",
            SourceStateSeed::Missing,
        )?;
        fixture.rewrite_source_state(
            &[
                swap(
                    "wallet-raw",
                    "sig-source-a",
                    parse_ts("2026-04-14T07:56:00Z")?,
                    SOL_MINT,
                    "TokenRaw111111111111111111111111111111111",
                    1.0,
                    10.0,
                ),
                swap(
                    "wallet-raw",
                    "sig-source-b",
                    parse_ts("2026-04-14T07:57:00Z")?,
                    SOL_MINT,
                    "TokenRaw111111111111111111111111111111111",
                    1.0,
                    11.0,
                ),
            ],
            parse_ts("2026-04-14T08:12:00Z")?,
        )?;
        fixture.write_promoted_surface_with_covered_since(
            "latest.sqlite",
            parse_ts("2026-04-14T07:55:00Z")?,
            2,
            parse_ts("2026-04-14T07:56:00Z")?,
            "sig-promoted",
            parse_ts("2026-04-14T08:00:00Z")?,
        )?;
        fixture.write_selected_staged_surface_sqlite_with_source_path_and_created_at(
            &fixture.runtime_db_path,
            &[swap(
                "wallet-raw",
                "sig-source-a",
                parse_ts("2026-04-14T07:56:00Z")?,
                SOL_MINT,
                "TokenRaw111111111111111111111111111111111",
                1.0,
                10.0,
            )],
            parse_ts("2026-04-14T08:10:00Z")?,
            parse_ts("2026-04-14T08:05:00Z")?,
        )?;

        let diagnostic =
            DiscoveryService::explain_recent_raw_replacement_progress_contract_read_only(
                &fixture.state_root,
            )?;
        assert!(diagnostic
            .recent_raw_replacement_candidate_created_at
            .is_some());
        assert!(diagnostic
            .recent_raw_replacement_candidate_covered_through
            .is_some());
        assert!(diagnostic
            .recent_raw_replacement_candidate_last_batch_completed_at
            .is_some());
        assert_eq!(
            diagnostic.recent_raw_replacement_candidate_completed_after_creation,
            Some(true)
        );
        assert_eq!(
            diagnostic.recent_raw_replacement_manifest_matches_sqlite_content,
            Some(true)
        );
        assert_eq!(diagnostic.recent_raw_replacement_candidate_advancing, None);
        assert!(!diagnostic
            .recent_raw_replacement_progress_explanation
            .is_empty());
        Ok(())
    }

    #[test]
    fn recent_raw_replacement_progress_contract_explain_remains_read_only_stage1() -> Result<()> {
        let fixture = make_recent_raw_promotion_fixture(
            "recent-raw-replacement-progress-contract-read-only",
            SourceStateSeed::Missing,
        )?;
        fixture.rewrite_source_state(
            &[
                swap(
                    "wallet-raw",
                    "sig-source-a",
                    parse_ts("2026-04-14T07:56:00Z")?,
                    SOL_MINT,
                    "TokenRaw111111111111111111111111111111111",
                    1.0,
                    10.0,
                ),
                swap(
                    "wallet-raw",
                    "sig-source-b",
                    parse_ts("2026-04-14T07:57:00Z")?,
                    SOL_MINT,
                    "TokenRaw111111111111111111111111111111111",
                    1.0,
                    11.0,
                ),
            ],
            parse_ts("2026-04-14T08:12:00Z")?,
        )?;
        fixture.write_promoted_surface_with_covered_since(
            "latest.sqlite",
            parse_ts("2026-04-14T07:55:00Z")?,
            2,
            parse_ts("2026-04-14T07:56:00Z")?,
            "sig-promoted",
            parse_ts("2026-04-14T08:00:00Z")?,
        )?;
        fixture.write_selected_staged_surface_sqlite_with_source_path_and_created_at(
            &fixture.runtime_db_path,
            &[swap(
                "wallet-raw",
                "sig-source-a",
                parse_ts("2026-04-14T07:56:00Z")?,
                SOL_MINT,
                "TokenRaw111111111111111111111111111111111",
                1.0,
                10.0,
            )],
            parse_ts("2026-04-14T08:10:00Z")?,
            parse_ts("2026-04-14T08:05:00Z")?,
        )?;

        let before = fixture.capture_bytes()?;
        let _ = DiscoveryService::explain_recent_raw_replacement_progress_contract_read_only(
            &fixture.state_root,
        )?;
        let after = fixture.capture_bytes()?;
        assert_eq!(before, after);
        Ok(())
    }
