#[test]
    fn recent_raw_promoted_retention_contract_matches_current_source_stage1() -> Result<()> {
        let fixture = make_recent_raw_promotion_fixture(
            "recent-raw-promoted-retention-contract-matches-current-source",
            SourceStateSeed::Missing,
        )?;
        fixture.rewrite_source_state(
            &[
                swap(
                    "wallet-raw",
                    "sig-source-a",
                    parse_ts("2026-04-14T07:55:00Z")?,
                    SOL_MINT,
                    "TokenRaw111111111111111111111111111111111",
                    1.0,
                    10.0,
                ),
                swap(
                    "wallet-raw",
                    "sig-source-b",
                    parse_ts("2026-04-14T07:56:00Z")?,
                    SOL_MINT,
                    "TokenRaw111111111111111111111111111111111",
                    1.0,
                    11.0,
                ),
            ],
            parse_ts("2026-04-14T08:06:00Z")?,
        )?;
        fixture.write_promoted_surface_with_covered_since(
            "latest.sqlite",
            parse_ts("2026-04-14T07:55:00Z")?,
            2,
            parse_ts("2026-04-14T07:56:00Z")?,
            "sig-source-b",
            parse_ts("2026-04-14T08:00:00Z")?,
        )?;

        let diagnostic =
            DiscoveryService::explain_recent_raw_promoted_retention_contract_read_only(
                &fixture.state_root,
            )?;
        assert_eq!(
            diagnostic.recent_raw_promoted_retention_reason_class,
            RecentRawPromotedRetentionReasonClass::RecentRawPromotedCurrentTruthMatchesCurrentSource
        );
        assert!(diagnostic.recent_raw_promoted_retention_observed);
        assert_eq!(
            diagnostic.recent_raw_promoted_start_older_than_current_source,
            Some(false)
        );
        assert_eq!(
            diagnostic.recent_raw_promoted_currently_retained_as_truth,
            Some(true)
        );
        assert_eq!(
            diagnostic.recent_raw_promoted_has_current_contract_invalidation_rule,
            Some(false)
        );
        assert_eq!(
            diagnostic.recent_raw_promoted_invalidated_by_current_source_window_shift,
            Some(false)
        );
        assert_eq!(
            diagnostic.recent_raw_stage3_truth_currently_depends_on_retained_older_promoted_surface,
            Some(false)
        );
        assert_eq!(
            diagnostic.recent_raw_stage3_truth_can_advance_without_new_promotion,
            Some(true)
        );
        assert_eq!(
            diagnostic.recent_raw_promoted_retention_basis,
            RecentRawPromotedRetentionBasis::MatchesCurrentSourceStart
        );
        Ok(())
    }

    #[test]
    fn recent_raw_promoted_retention_contract_retains_older_promoted_stage1() -> Result<()> {
        let fixture = make_recent_raw_promotion_fixture(
            "recent-raw-promoted-retention-contract-retains-older-promoted",
            SourceStateSeed::Missing,
        )?;
        fixture.rewrite_source_state(
            &[
                swap(
                    "wallet-raw",
                    "sig-source-old",
                    parse_ts("2026-04-14T07:54:00Z")?,
                    SOL_MINT,
                    "TokenRaw111111111111111111111111111111111",
                    1.0,
                    9.0,
                ),
                swap(
                    "wallet-raw",
                    "sig-source-a",
                    parse_ts("2026-04-14T07:56:00Z")?,
                    SOL_MINT,
                    "TokenRaw111111111111111111111111111111111",
                    1.0,
                    10.0,
                ),
                swap(
                    "wallet-raw",
                    "sig-source-b",
                    parse_ts("2026-04-14T07:57:00Z")?,
                    SOL_MINT,
                    "TokenRaw111111111111111111111111111111111",
                    1.0,
                    11.0,
                ),
            ],
            parse_ts("2026-04-14T08:06:00Z")?,
        )?;
        fixture.prune_source_state_before(
            parse_ts("2026-04-14T07:56:00Z")?,
            32,
            parse_ts("2026-04-14T08:07:00Z")?,
        )?;
        fixture.write_promoted_surface_with_covered_since(
            "latest.sqlite",
            parse_ts("2026-04-14T07:55:00Z")?,
            2,
            parse_ts("2026-04-14T07:57:00Z")?,
            "sig-promoted",
            parse_ts("2026-04-14T08:00:00Z")?,
        )?;

        let diagnostic =
            DiscoveryService::explain_recent_raw_promoted_retention_contract_read_only(
                &fixture.state_root,
            )?;
        assert_eq!(
            diagnostic.recent_raw_promoted_retention_reason_class,
            RecentRawPromotedRetentionReasonClass::RecentRawPromotedRetainedByDesignDespiteOlderWindow
        );
        assert!(diagnostic.recent_raw_promoted_retention_observed);
        assert_eq!(
            diagnostic.recent_raw_promoted_start_older_than_current_source,
            Some(true)
        );
        assert_eq!(
            diagnostic.recent_raw_promoted_currently_retained_as_truth,
            Some(true)
        );
        assert_eq!(
            diagnostic.recent_raw_promoted_has_current_contract_invalidation_rule,
            Some(false)
        );
        assert_eq!(
            diagnostic.recent_raw_promoted_invalidated_by_current_source_window_shift,
            Some(false)
        );
        assert_eq!(
            diagnostic.recent_raw_stage3_truth_currently_depends_on_retained_older_promoted_surface,
            Some(true)
        );
        assert_eq!(
            diagnostic.recent_raw_stage3_truth_can_advance_without_new_promotion,
            Some(false)
        );
        assert_eq!(
            diagnostic.recent_raw_promoted_retention_basis,
            RecentRawPromotedRetentionBasis::FixedPromotedLatestRetainedUntilReplacement
        );
        assert_eq!(
            diagnostic.recent_raw_promotion_reason_class,
            RecentRawPromotionBlockerReasonClass::RecentRawPromotionBlockedByMissingStagedSnapshot
        );
        Ok(())
    }

    #[test]
    fn recent_raw_promoted_retention_contract_exposes_no_shift_invalidation_rule_stage1(
    ) -> Result<()> {
        let fixture = make_recent_raw_promotion_fixture(
            "recent-raw-promoted-retention-contract-no-invalidation-rule",
            SourceStateSeed::Missing,
        )?;
        fixture.rewrite_source_state(
            &[
                swap(
                    "wallet-raw",
                    "sig-source-old",
                    parse_ts("2026-04-14T07:54:00Z")?,
                    SOL_MINT,
                    "TokenRaw111111111111111111111111111111111",
                    1.0,
                    9.0,
                ),
                swap(
                    "wallet-raw",
                    "sig-source-a",
                    parse_ts("2026-04-14T07:56:00Z")?,
                    SOL_MINT,
                    "TokenRaw111111111111111111111111111111111",
                    1.0,
                    10.0,
                ),
                swap(
                    "wallet-raw",
                    "sig-source-b",
                    parse_ts("2026-04-14T07:57:00Z")?,
                    SOL_MINT,
                    "TokenRaw111111111111111111111111111111111",
                    1.0,
                    11.0,
                ),
            ],
            parse_ts("2026-04-14T08:06:00Z")?,
        )?;
        fixture.prune_source_state_before(
            parse_ts("2026-04-14T07:56:00Z")?,
            32,
            parse_ts("2026-04-14T08:07:00Z")?,
        )?;
        fixture.write_promoted_surface_with_covered_since(
            "latest.sqlite",
            parse_ts("2026-04-14T07:55:00Z")?,
            2,
            parse_ts("2026-04-14T07:57:00Z")?,
            "sig-promoted",
            parse_ts("2026-04-14T08:00:00Z")?,
        )?;

        let diagnostic =
            DiscoveryService::explain_recent_raw_promoted_retention_contract_read_only(
                &fixture.state_root,
            )?;
        assert_eq!(
            diagnostic.recent_raw_promoted_has_current_contract_invalidation_rule,
            Some(false)
        );
        assert_eq!(
            diagnostic.recent_raw_promoted_invalidated_by_current_source_window_shift,
            Some(false)
        );
        assert!(diagnostic
            .recent_raw_promoted_retention_basis_explanation
            .contains("does not retire promoted latest"));
        Ok(())
    }
