use super::*;

#[derive(Debug)]
pub(in crate::source) struct IngestionTelemetry {
    pub(in crate::source) ws_notifications_seen: AtomicU64,
    pub(in crate::source) ws_notifications_enqueued: AtomicU64,
    pub(in crate::source) ws_notifications_backpressured: AtomicU64,
    pub(in crate::source) ws_notifications_dropped: AtomicU64,
    pub(in crate::source) ws_notifications_replaced_oldest: AtomicU64,
    pub(in crate::source) reconnect_count: AtomicU64,
    pub(in crate::source) stream_gap_detected: AtomicU64,
    pub(in crate::source) parse_rejected_total: AtomicU64,
    pub(in crate::source) parse_rejected_by_reason: Mutex<BTreeMap<&'static str, u64>>,
    pub(in crate::source) parse_fallback_by_reason: Mutex<BTreeMap<&'static str, u64>>,
    pub(in crate::source) grpc_message_total: AtomicU64,
    pub(in crate::source) grpc_transaction_updates_total: AtomicU64,
    pub(in crate::source) grpc_decode_errors: AtomicU64,
    pub(in crate::source) fetch_inflight: AtomicU64,
    pub(in crate::source) fetch_success: AtomicU64,
    pub(in crate::source) fetch_failed: AtomicU64,
    pub(in crate::source) fetch_no_swap: AtomicU64,
    pub(in crate::source) fetch_retry_attempts: AtomicU64,
    pub(in crate::source) fetch_retry_exhausted: AtomicU64,
    pub(in crate::source) fetch_retry_terminal: AtomicU64,
    pub(in crate::source) prefetch_stale_dropped: AtomicU64,
    pub(in crate::source) rpc_429: AtomicU64,
    pub(in crate::source) rpc_5xx: AtomicU64,
    pub(in crate::source) last_ingestion_lag_p95: AtomicU64,
    pub(in crate::source) last_yellowstone_output_queue_depth: AtomicU64,
    pub(in crate::source) last_yellowstone_output_queue_capacity: AtomicU64,
    pub(in crate::source) last_yellowstone_output_oldest_age_ms: AtomicU64,
    pub(in crate::source) fetch_latency_ms_samples: Mutex<VecDeque<u64>>,
    pub(in crate::source) ingestion_lag_ms_samples: Mutex<VecDeque<u64>>,
    pub(in crate::source) reorder_hold_ms_samples: Mutex<VecDeque<u64>>,
    pub(in crate::source) max_reorder_buffer_size: AtomicUsize,
    pub(in crate::source) last_report_ms: AtomicI64,
}

impl Default for IngestionTelemetry {
    fn default() -> Self {
        Self {
            ws_notifications_seen: AtomicU64::new(0),
            ws_notifications_enqueued: AtomicU64::new(0),
            ws_notifications_backpressured: AtomicU64::new(0),
            ws_notifications_dropped: AtomicU64::new(0),
            ws_notifications_replaced_oldest: AtomicU64::new(0),
            reconnect_count: AtomicU64::new(0),
            stream_gap_detected: AtomicU64::new(0),
            parse_rejected_total: AtomicU64::new(0),
            parse_rejected_by_reason: Mutex::new(BTreeMap::new()),
            parse_fallback_by_reason: Mutex::new(BTreeMap::new()),
            grpc_message_total: AtomicU64::new(0),
            grpc_transaction_updates_total: AtomicU64::new(0),
            grpc_decode_errors: AtomicU64::new(0),
            fetch_inflight: AtomicU64::new(0),
            fetch_success: AtomicU64::new(0),
            fetch_failed: AtomicU64::new(0),
            fetch_no_swap: AtomicU64::new(0),
            fetch_retry_attempts: AtomicU64::new(0),
            fetch_retry_exhausted: AtomicU64::new(0),
            fetch_retry_terminal: AtomicU64::new(0),
            prefetch_stale_dropped: AtomicU64::new(0),
            rpc_429: AtomicU64::new(0),
            rpc_5xx: AtomicU64::new(0),
            last_ingestion_lag_p95: AtomicU64::new(0),
            last_yellowstone_output_queue_depth: AtomicU64::new(0),
            last_yellowstone_output_queue_capacity: AtomicU64::new(0),
            last_yellowstone_output_oldest_age_ms: AtomicU64::new(0),
            fetch_latency_ms_samples: Mutex::new(VecDeque::with_capacity(
                TELEMETRY_SAMPLE_CAPACITY,
            )),
            ingestion_lag_ms_samples: Mutex::new(VecDeque::with_capacity(
                TELEMETRY_SAMPLE_CAPACITY,
            )),
            reorder_hold_ms_samples: Mutex::new(VecDeque::with_capacity(TELEMETRY_SAMPLE_CAPACITY)),
            max_reorder_buffer_size: AtomicUsize::new(0),
            last_report_ms: AtomicI64::new(0),
        }
    }
}
