use super::*;

#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum RecentRawPromotionBlockerReasonClass {
    RecentRawPromotionReadyNow,
    RecentRawPromotionBlockedByMissingStagedSnapshot,
    RecentRawPromotionBlockedByIncompleteStagedCoverage,
    RecentRawPromotionBlockedByStagedNotNewerThanPromoted,
    RecentRawPromotionBlockedByMissingPromotedLatest,
    RecentRawPromotionBlockedByUnprovenState,
    RecentRawPromotionNotNeededPromotedAlreadyCurrent,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct RecentRawPromotionBlockerDiagnostic {
    pub recent_raw_snapshot_dir: String,
    pub recent_raw_promotion_blocker_observed: bool,
    pub recent_raw_promotion_ready_now: bool,
    pub recent_raw_promotion_reason_class: RecentRawPromotionBlockerReasonClass,
    pub recent_raw_promotion_explanation: String,
    pub recent_raw_promoted_exists: bool,
    pub recent_raw_promoted_snapshot_present: bool,
    pub recent_raw_promoted_metadata_present: bool,
    pub recent_raw_promoted_created_at: Option<DateTime<Utc>>,
    pub recent_raw_promoted_covered_since: Option<DateTime<Utc>>,
    pub recent_raw_promoted_covered_through: Option<DiscoveryRuntimeCursor>,
    pub recent_raw_promoted_row_count: Option<usize>,
    pub recent_raw_promoted_last_batch_completed_at: Option<DateTime<Utc>>,
    pub recent_raw_staged_exists: bool,
    pub recent_raw_staged_snapshot_present: bool,
    pub recent_raw_staged_metadata_present: bool,
    pub recent_raw_staged_created_at: Option<DateTime<Utc>>,
    pub recent_raw_staged_covered_since: Option<DateTime<Utc>>,
    pub recent_raw_staged_covered_through: Option<DiscoveryRuntimeCursor>,
    pub recent_raw_staged_row_count: Option<usize>,
    pub recent_raw_staged_last_batch_completed_at: Option<DateTime<Utc>>,
    pub recent_raw_staged_newer_than_promoted: Option<bool>,
    pub recent_raw_runtime_db_path: Option<String>,
    pub recent_raw_runtime_db_size_bytes: Option<u64>,
    pub recent_raw_runtime_db_mtime: Option<String>,
    pub recent_raw_runtime_db_wal_present: bool,
    pub recent_raw_runtime_db_wal_size_bytes: Option<u64>,
    pub recent_raw_source_state_available: bool,
    pub recent_raw_source_row_count: Option<usize>,
    pub recent_raw_source_covered_since: Option<DateTime<Utc>>,
    pub recent_raw_source_covered_through: Option<DiscoveryRuntimeCursor>,
    pub recent_raw_source_last_batch_completed_at: Option<DateTime<Utc>>,
    pub recent_raw_source_outruns_staged: Option<bool>,
    pub recent_raw_source_outruns_promoted: Option<bool>,
    pub recent_raw_stage3_truth_blocked_by_promotion: bool,
    pub recent_raw_stage3_current_fresh_healthy_evidence_possible: bool,
}

#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum RecentRawCatchUpReasonClass {
    RecentRawCatchUpProgressingButNotCaughtUp,
    RecentRawCatchUpStalled,
    RecentRawCatchUpLosingToSource,
    RecentRawCatchUpCaughtUp,
    RecentRawCatchUpUnprovenDueToMissingEvidence,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct RecentRawCatchUpDiagnostic {
    pub recent_raw_snapshot_dir: String,
    pub recent_raw_catch_up_status_observed: bool,
    pub recent_raw_catch_up_reason_class: RecentRawCatchUpReasonClass,
    pub recent_raw_catch_up_explanation: String,
    pub recent_raw_promoted_exists: bool,
    pub recent_raw_promoted_created_at: Option<DateTime<Utc>>,
    pub recent_raw_promoted_covered_through: Option<DiscoveryRuntimeCursor>,
    pub recent_raw_promoted_row_count: Option<usize>,
    pub recent_raw_promoted_last_batch_completed_at: Option<DateTime<Utc>>,
    pub recent_raw_staged_exists: bool,
    pub recent_raw_staged_created_at: Option<DateTime<Utc>>,
    pub recent_raw_staged_covered_through: Option<DiscoveryRuntimeCursor>,
    pub recent_raw_staged_row_count: Option<usize>,
    pub recent_raw_staged_last_batch_completed_at: Option<DateTime<Utc>>,
    pub recent_raw_staged_advancing: Option<bool>,
    pub recent_raw_staged_ahead_of_promoted: Option<bool>,
    pub recent_raw_staged_last_batch_completed_at_newer_than_promoted: Option<bool>,
    pub recent_raw_source_state_available: bool,
    pub recent_raw_source_covered_through: Option<DiscoveryRuntimeCursor>,
    pub recent_raw_source_row_count: Option<usize>,
    pub recent_raw_source_last_batch_completed_at: Option<DateTime<Utc>>,
    pub recent_raw_runtime_db_path: Option<String>,
    pub recent_raw_runtime_db_size_bytes: Option<u64>,
    pub recent_raw_runtime_db_mtime: Option<String>,
    pub recent_raw_runtime_db_wal_present: bool,
    pub recent_raw_runtime_db_wal_size_bytes: Option<u64>,
    pub recent_raw_source_vs_staged_row_lag: Option<u64>,
    pub recent_raw_source_vs_promoted_row_lag: Option<u64>,
    pub recent_raw_source_vs_staged_time_lag_seconds: Option<u64>,
    pub recent_raw_source_vs_promoted_time_lag_seconds: Option<u64>,
    pub recent_raw_staged_vs_promoted_row_delta: Option<i64>,
    pub recent_raw_staged_vs_promoted_time_delta_seconds: Option<i64>,
    pub recent_raw_catch_up_progressing: bool,
    pub recent_raw_catch_up_losing_to_source: bool,
    pub recent_raw_catch_up_indeterminate: bool,
}
