#[derive(Debug, Clone, Default, PartialEq)]
pub(crate) struct ExecutionQuoteCanaryTickSummary {
    pub(crate) source_sell_refusals: crate::execution_canary_summary::SourceSellWriteOffRefusals,
    pub strict_running: usize,
    pub strict_completed: usize,
    pub strict_errors: usize,
    pub strict_capacity_refused: usize,
    pub entry_candidates: usize,
    pub entry_inserted: usize,
    pub entry_existing: usize,
    pub entry_errors: usize,
    pub close_candidates: usize,
    pub close_inserted: usize,
    pub close_existing: usize,
    pub close_errors: usize,
    pub would_execute: usize,
    pub would_force_exit: usize,
    pub would_skip: usize,
    pub decision_unknown: usize,
    pub last_event_id: Option<String>,
    pub last_error: Option<String>,
    pub last_owned_sell_recovery_error: Option<crate::telemetry::OwnedSellRecoveryError>,
}
