const DEFAULT_CONFIG_PATH: &str = "configs/dev.toml";
const SHADOW_WORKER_POOL_SIZE: usize = 4;
const SHADOW_INLINE_WORKER_OVERFLOW: usize = 1;
const SHADOW_MAX_CONCURRENT_WORKERS: usize =
    SHADOW_WORKER_POOL_SIZE + SHADOW_INLINE_WORKER_OVERFLOW;
const SHADOW_PENDING_TASK_CAPACITY: usize = 256;
const INGESTION_ERROR_BACKOFF_MS: [u64; 6] = [100, 250, 500, 1_000, 2_000, 5_000];
const RISK_DB_REFRESH_MIN_SECONDS: i64 = 5;
const RISK_INFRA_SAMPLE_MIN_SECONDS: i64 = 10;
const RISK_FAIL_CLOSED_LOG_THROTTLE_SECONDS: i64 = 60;
const RISK_INFRA_EVENT_THROTTLE_SECONDS: i64 = 300;
const RISK_INFRA_ACTIVATE_CONSECUTIVE_SAMPLES: u64 = 5;
const RISK_INFRA_CLEAR_HEALTHY_SAMPLES: u64 = 5;
const RECENT_SWAP_SIGNATURE_DEDUPE_CAPACITY: usize = 32_768;
const APP_CONSUMER_LOOP_LATENCY_SAMPLE_CAPACITY: usize = 512;
const DISCOVERY_CRITICAL_TARGET_BUY_MINTS_BACKPRESSURE_REFRESH_INTERVAL: StdDuration =
    StdDuration::from_secs(1);
const DISCOVERY_CRITICAL_PENDING_IRRELEVANT_SWAP_CAPACITY: usize =
    OBSERVED_SWAP_WRITER_CHANNEL_CAPACITY;
const NONCRITICAL_IRRELEVANT_OUTPUT_PRESSURE_DROP_MIN_FILL_RATIO: f64 = 0.5;
const ZERO_UNIVERSE_EMPTY_TARGET_NONCRITICAL_BEST_EFFORT_REFILL_COOLDOWN: StdDuration =
    StdDuration::from_secs(30);
const STALE_LOT_CLEANUP_BATCH_LIMIT: u32 = 300;
const HARD_STOP_CLEAR_HEALTHY_REFRESHES: u64 = 6;
const SQLITE_MAINTENANCE_MAX_YELLOWSTONE_OUTPUT_QUEUE_FILL_RATIO: f64 = 0.25;
const SQLITE_MAINTENANCE_PARTIAL_RETRY_INTERVAL: Duration = Duration::from_secs(60);
const DEFAULT_INGESTION_OVERRIDE_PATH: &str = "state/ingestion_source_override.env";
const DEFAULT_OPERATOR_EMERGENCY_STOP_PATH: &str = "state/operator_emergency_stop.flag";
const DEFAULT_OPERATOR_EMERGENCY_STOP_POLL_MS: u64 = 500;
const APP_LOG_FILTER_ENV: &str = "COPYBOT_APP_LOG_FILTER";
const LEGACY_RUST_LOG_ENV: &str = "RUST_LOG";
const LAMPORTS_PER_SOL: f64 = 1_000_000_000.0;
const OBSERVED_SWAP_WRITER_BACKPRESSURE_RETRY_INTERVAL: Duration = Duration::from_millis(50);
const OBSERVED_SWAP_WRITER_BACKPRESSURE_LOG_THROTTLE: StdDuration = StdDuration::from_secs(5);
#[cfg(test)]
static APP_ENV_LOCK: Mutex<()> = Mutex::new(());
