use super::*;

fn config(mode: Mode, path: PathBuf) -> Config {
    Config {
        mode,
        path,
        reason: None,
        force: false,
        confirm_clear: None,
        json: true,
    }
}

fn test_dir(name: &str) -> Result<PathBuf> {
    let path = env::temp_dir().join(format!(
        "copybot_operator_emergency_stop_{name}_{}_{}",
        std::process::id(),
        Utc::now().timestamp_nanos_opt().unwrap_or_default()
    ));
    fs::create_dir_all(&path)?;
    Ok(path)
}

#[test]
fn missing_flag_status_reports_inactive_stage4() -> Result<()> {
    let temp = test_dir("missing_status")?;
    let path = temp.join("stop.flag");

    let report = run(config(Mode::Status, path))?.output;

    assert!(!report.active);
    assert!(!report.changed);
    assert_eq!(report.reason, None);
    assert_eq!(report.verdict, "inactive_missing");
    Ok(())
}

#[test]
fn active_flag_status_parses_first_non_comment_reason_stage4() -> Result<()> {
    let temp = test_dir("active_status")?;
    let path = temp.join("stop.flag");
    fs::write(
        &path,
        "\n# generated by operator\n  stop buys during incident  \nsecond line\n",
    )?;

    let report = run(config(Mode::Status, path))?.output;

    assert!(report.active);
    assert_eq!(report.reason.as_deref(), Some("stop buys during incident"));
    assert_eq!(report.verdict, "active");
    Ok(())
}

#[cfg(unix)]
#[test]
fn unreadable_existing_flag_status_is_active_fail_closed_stage4() -> Result<()> {
    use std::os::unix::fs::PermissionsExt;

    let temp = test_dir("unreadable_status")?;
    let path = temp.join("stop.flag");
    fs::write(&path, "incident\n")?;
    let original_permissions = fs::metadata(&path)?.permissions();
    fs::set_permissions(&path, fs::Permissions::from_mode(0o000))?;

    let report = run(config(Mode::Status, path.clone()))?.output;

    fs::set_permissions(&path, original_permissions)?;
    assert!(report.active);
    assert_eq!(report.verdict, "active_fail_closed_unreadable");
    assert!(report
        .reason
        .as_deref()
        .unwrap_or_default()
        .contains("unreadable"));
    Ok(())
}

#[test]
fn activate_writes_expected_reason_stage4() -> Result<()> {
    let temp = test_dir("activate_writes")?;
    let path = temp.join("nested").join("stop.flag");
    let mut cfg = config(Mode::Activate, path.clone());
    cfg.reason = Some("incident stop".to_string());

    let report = run(cfg)?.output;

    assert!(report.active);
    assert!(report.changed);
    assert_eq!(report.reason.as_deref(), Some("incident stop"));
    assert_eq!(
        parse_operator_emergency_stop_reason(&fs::read_to_string(path)?).as_deref(),
        Some("incident stop")
    );
    Ok(())
}

#[test]
fn activate_same_reason_is_idempotent_stage4() -> Result<()> {
    let temp = test_dir("activate_idempotent")?;
    let path = temp.join("stop.flag");
    fs::write(&path, "incident stop\n# existing metadata\n")?;
    let mut cfg = config(Mode::Activate, path.clone());
    cfg.reason = Some("incident stop".to_string());

    let report = run(cfg)?.output;

    assert!(report.active);
    assert!(!report.changed);
    assert_eq!(report.reason.as_deref(), Some("incident stop"));
    assert_eq!(report.verdict, "already_active_same_reason");
    assert_eq!(
        fs::read_to_string(path)?,
        "incident stop\n# existing metadata\n"
    );
    Ok(())
}

#[test]
fn activate_refuses_different_reason_without_force_stage4() -> Result<()> {
    let temp = test_dir("activate_refuses")?;
    let path = temp.join("stop.flag");
    fs::write(&path, "old incident\n")?;
    let mut cfg = config(Mode::Activate, path.clone());
    cfg.reason = Some("new incident".to_string());

    let report = run(cfg)?.output;

    assert!(report.active);
    assert!(!report.changed);
    assert_eq!(report.reason.as_deref(), Some("old incident"));
    assert_eq!(report.verdict, "activate_refused_different_reason");
    assert_eq!(fs::read_to_string(path)?, "old incident\n");
    Ok(())
}

#[test]
fn activate_with_force_overwrites_different_reason_stage4() -> Result<()> {
    let temp = test_dir("activate_force")?;
    let path = temp.join("stop.flag");
    fs::write(&path, "old incident\n")?;
    let mut cfg = config(Mode::Activate, path.clone());
    cfg.reason = Some("new incident".to_string());
    cfg.force = true;

    let report = run(cfg)?.output;

    assert!(report.active);
    assert!(report.changed);
    assert_eq!(report.reason.as_deref(), Some("new incident"));
    assert_eq!(report.verdict, "activated_force_overwrote_reason");
    assert_eq!(
        parse_operator_emergency_stop_reason(&fs::read_to_string(path)?).as_deref(),
        Some("new incident")
    );
    Ok(())
}

#[test]
fn clear_requires_exact_confirmation_stage4() -> Result<()> {
    let temp = test_dir("clear_requires_confirmation")?;
    let path = temp.join("stop.flag");
    fs::write(&path, "incident\n")?;
    let mut cfg = config(Mode::Clear, path.clone());
    cfg.confirm_clear = Some("wrong".to_string());

    let report = run(cfg)?.output;

    assert!(report.active);
    assert!(!report.changed);
    assert_eq!(report.verdict, "clear_refused_missing_confirmation");
    assert!(path.exists());
    Ok(())
}

#[test]
fn clear_is_idempotent_when_missing_stage4() -> Result<()> {
    let temp = test_dir("clear_idempotent")?;
    let path = temp.join("stop.flag");
    let mut cfg = config(Mode::Clear, path);
    cfg.confirm_clear = Some(CLEAR_CONFIRMATION.to_string());

    let report = run(cfg)?.output;

    assert!(!report.active);
    assert!(!report.changed);
    assert_eq!(report.verdict, "already_clear");
    Ok(())
}
