use super::*;

pub(crate) fn append_render_staged_write(lines: &mut Vec<String>, output: &SnapshotOutput) {
    lines.extend([
        format!(
            "staged_write_batch_count={}",
            output.staged_write_batch_count
        ),
        format!("staged_write_batch_rows={}", output.staged_write_batch_rows),
        format!(
            "staged_write_sqlite_variable_limit={}",
            output.staged_write_sqlite_variable_limit
        ),
        format!(
            "staged_write_statement_params_per_row={}",
            output.staged_write_statement_params_per_row
        ),
        format!(
            "staged_write_statement_chunk_row_cap={}",
            output.staged_write_statement_chunk_row_cap
        ),
        format!(
            "staged_write_effective_statement_chunk_rows={}",
            output.staged_write_effective_statement_chunk_rows
        ),
        format!(
            "staged_write_statement_count={}",
            output.staged_write_statement_count
        ),
        format!(
            "staged_write_rows_processed={}",
            output.staged_write_rows_processed
        ),
        format!(
            "staged_write_rows_inserted={}",
            output.staged_write_rows_inserted
        ),
        format!(
            "staged_write_value_build_duration_ms={}",
            output.staged_write_value_build_duration_ms
        ),
        format!(
            "staged_write_prepare_duration_ms={}",
            output.staged_write_prepare_duration_ms
        ),
        format!(
            "staged_write_execute_duration_ms={}",
            output.staged_write_execute_duration_ms
        ),
        format!(
            "staged_write_state_refresh_duration_ms={}",
            output.staged_write_state_refresh_duration_ms
        ),
        format!(
            "staged_write_state_upsert_duration_ms={}",
            output.staged_write_state_upsert_duration_ms
        ),
        format!(
            "staged_write_transaction_duration_ms={}",
            output.staged_write_transaction_duration_ms
        ),
        format!(
            "staged_write_deadline_exhausted_before_statement={}",
            output.staged_write_deadline_exhausted_before_statement
        ),
        format!(
            "staged_write_deadline_exhausted_during_execute={}",
            output.staged_write_deadline_exhausted_during_execute
        ),
    ]);
}
