use anyhow::Result;
use copybot_storage_core::{association_inbox::*, SqliteStore};
use std::path::PathBuf;
#[test]
#[ignore = "exact filled SQLite databases generated by accepted90/R1 actual consumer"]
fn b91_full_accepted90r1_databases_migrate_reopen_drain_at_same_limits() -> Result<()> {
    let root = PathBuf::from(std::env::var("B91_BASELINE_DB_DIR")?);
    let out = PathBuf::from(std::env::var("B89_DB_DIR")?);
    std::fs::create_dir_all(&out)?;
    let mut count = 0;
    for entry in std::fs::read_dir(root)? {
        let meta_path = entry?.path();
        if !meta_path.to_string_lossy().ends_with(".upgrade.json") {
            continue;
        }
        let m: serde_json::Value = serde_json::from_slice(&std::fs::read(&meta_path)?)?;
        let source = meta_path.with_extension("").with_extension("sqlite");
        let path = out.join(format!(
            "upgraded-{}",
            source.file_name().unwrap().to_string_lossy()
        ));
        assert!(!path.exists());
        std::fs::copy(&source, &path)?;
        let mut store = SqliteStore::open(&path)?;
        store
            .run_migrations(&PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../migrations"))?;
        let limits = InboxLimits {
            count: m["count"].as_u64().unwrap() as usize,
            bytes: m["bytes"].as_u64().unwrap() as usize,
            busy_ms: 100,
        };
        let mut inbox = AssociationInbox::open(&path, limits)?;
        assert_eq!(inbox.usage()?, (limits.count, limits.bytes));
        while inbox.has_sell_preparation_work()? {
            inbox.recover_sell_preparation()?;
        }
        assert_eq!(inbox.usage()?, (limits.count, limits.bytes));
        let p = inbox
            .sell_preparation(m["signature"].as_str().unwrap())?
            .unwrap();
        assert_eq!(serde_json::to_value(p.first)?, m["first"]);
        assert_eq!(
            serde_json::to_value(p.current.selected_chain)?,
            serde_json::json!({"Unknown":"ParentGap"})
        );
        assert_eq!(
            serde_json::to_value(p.historical_latest.selected_chain)?,
            serde_json::json!({"Unknown":"ParentGap"})
        );
        let sql = rusqlite::Connection::open(&path)?;
        assert_eq!(
            sql.query_row(
                "SELECT count(*) FROM association_parent_dependencies",
                [],
                |r| r.get::<_, i64>(0)
            )?,
            0
        );
        count += 1;
    }
    assert_eq!(count, 4);
    Ok(())
}
